
CREATE SCHEMA test_schema AUTHORIZATION sa;
CREATE TABLE ROOM (
ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
NAME VARCHAR(16) NOT NULL,
ROOM_NUMBER VARCHAR(2) NOT NULL UNIQUE ,
BED_INFO VARCHAR(2) NOT NULL
)